# Generated by Django 3.2.7 on 2021-10-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0003_alter_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooluser',
            name='gh_stars',
        ),
    ]
