# Generated by Django 3.2.7 on 2022-11-13 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0003_auto_20221111_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
