# Generated by Django 3.2.7 on 2022-11-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0004_auto_20221108_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooluser',
            name='github_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cooluser',
            name='gravatar_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_link',
            field=models.URLField(null=True),
        ),
    ]
