# Generated by Django 3.2.7 on 2022-11-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0004_rename_auther_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooluser',
            name='github_prof',
        ),
        migrations.AddField(
            model_name='cooluser',
            name='github_profile',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='cooluser',
            name='gravatar_link',
            field=models.URLField(null=True),
        ),
    ]
