# Generated by Django 3.2.7 on 2021-10-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0005_remove_post_chart_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
