# Generated by Django 3.2.7 on 2022-11-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0005_auto_20221109_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooluser',
            name='gh_repositories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
