# Generated by Django 3.2.7 on 2022-11-15 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0007_rename_posts_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='cooluser',
            name='github_repo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img_link',
        ),
        migrations.AddField(
            model_name='cooluser',
            name='gh_repositories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='cooluser',
            name='github_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cooluser',
            name='gravatar_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Pasdfasdfublished Post')], default='DRAFT', max_length=32),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('PUBLISHED', 'Published'), ('NON_PUBLISHED', 'Non Published')], default='PUBLISHED', max_length=32)),
                ('votes', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='press.cooluser')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='press.post')),
            ],
        ),
    ]
