# Generated by Django 3.2.7 on 2022-11-17 16:30

from django.db import migrations, models
import press.models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0008_auto_20221115_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(press.models.PostStatus['DRAFT'], 'Draft'), (press.models.PostStatus['PUBLISHED'], 'Pasdfasdfublished Post')], default=press.models.PostStatus['DRAFT'], max_length=32),
        ),
    ]
