# Generated by Django 3.2.7 on 2022-11-22 22:42

from django.db import migrations, models
import press.models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0009_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooluser',
            name='github_profile',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(press.models.PostStatus['DRAFT'], 'DRAFT'), (press.models.PostStatus['PUBLISHED'], 'PUBLISHED')], default=press.models.PostStatus['DRAFT'], max_length=32),
        ),
    ]
