# Generated by Django 3.2.7 on 2022-11-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0010_auto_20221122_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooluser',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
