# Generated by Django 3.2.7 on 2022-11-23 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0011_cooluser_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooluser',
            name='last_update',
        ),
        migrations.AddField(
            model_name='cooluser',
            name='gravatar_updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
