# Generated by Django 3.2.7 on 2022-11-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0012_auto_20221123_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooluser',
            name='gh_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
